Use ImportMeta type instead of custom type
martonlederer/dirname pull request #1
Opened 2020-10-07 20:16 UTC by shadowtime2000

2020-10-08 04:47 UTC, martonlederer requested changes
Thanks for updating with the actual ImportMeta type. Didn't know it existed...
Could you please remove the formatting? I intentionally didn't use Deno fmt, because it's not really clean to me

2020-10-09 22:53 UTC, shadowtime2000 commented
> Thanks for updating with the actual ImportMeta type. Didn't know it existed...
> Could you please remove the formatting? I intentionally didn't use Deno fmt, because it's not really clean to me

@martonlederer Done!

2020-10-10 05:42 UTC, martonlederer commented
Thank you for your contribution :)

2020-10-10 05:42 UTC, martonlederer approved these changes

2020-10-10 05:43 UTC, merged